### ISSUE TITLE
Pagination is broken

### ISSUE THREAD

**Issue by opatdchan** [dchan-network/dchan-client#16]
Always returns Page 1 of 1 despite having multiple pages

**Comment by Frawstcrabs** [comment]
Seems to work fine on prod, though.
![firefox_iBj2Fy4ziL](https://user-images.githubusercontent.com/7711703/135605322-173ece41-59c0-467a-8723-99ea013328af.png)

**Comment by opatdchan** [comment]
nvm im a dumbass
