### ISSUE TITLE
Backlinks broken

### ISSUE THREAD

**Issue by opatdchan** [dchan-network/dchan-client#20]
Sometimes when clicking on a backlink nothing happens, but only sometimes.

**Comment by Frawstcrabs** [comment]
Also the massive lag between clicking on a backlink and focus actually changing is back.

**Comment by Frawstcrabs** [comment]
Note to self on lag issue: useBlockNumber triggers a re-render each time the URL changes, and this means Posts will all re-render despite everything else staying constant, which defeats the purpose of wrapping Posts in a memo. Passing block number as a prop is the far more performant solution.

**Comment by opatdchan** [comment]
I suppose this doesn't happen anymore.
