### ISSUE TITLE
I have a design idea that could make dchan function without any fees

### ISSUE THREAD

**Issue by estebanabaroa** [dchan-network/dchan-client#7]
I posted about my idea here https://discuss.ipfs.io/t/design-idea-to-solve-the-scalability-problem-of-a-decentralized-social-media-platform-using-ipfs/12158/7

The design describes a Reddit alternative, but I believe the design would also work perfectly for dchan. Feel free to use any idea from it without crediting me.

I will copy paste it below (but replace the Reddit analogies with 4chan ones instead):

**Title: A serverless, adminless, decentralized 4chan alternative**

**Abstract**

A decentralized social media has 2 problems: How to store the entire world's data on a blockchain, and how to prevent spam while being feeless. We propose solving the data problem by not using a blockchain, but rather "public key based addressing" and a peer-to-peer pubsub network. A blockchain or even a DAG is unnecessary because unlike cryptocurrencies that must know the order of each transaction to prevent double spends, social media does not care about the order of posts, nor about the availability of old posts. We propose solving the spam problem by having each 4chan board owner run their own "captcha server" and ignore posts that don't contain a valid captcha challenge answer.

**Public key based addressing**

In Bittorrent, you have "content based addressing". The hash of a file becomes its address. With "public key based addressing", the hash of a public key becomes the address of the 4chan board. Network peers perform a DHT query of this address to retrieve the content of the 4chan board. Each time the content gets updated, the nonce of the content increases. The network only keeps the latest nonce.

**Peer-to-peer pubsub**

Pubsub is an architecture where you subscribe to a "topic", like "cats", then whenever someone publishes a message of topic "cat", you receive it. A peer-to-peer pubsub network means that anyone can publish, and anyone can subscribe. To publish a post to a 4chan board, a user would publish a message with a "topic" equal to the 4chan board public key (its public key based addressing).

**Captcha server**

A "captcha server" is a URL that prompts the user to perform a captcha challenge before a post, then sends him a valid signature if completed successfully. The captcha server can decide to prompt all users, first time users only, or no users at all. The captcha server implementation is completely up to the subplebbit owner. He can use 3rd party services like Google captchas.

**Lifecycle of creating a 4chan board**

1. Board owner starts a 4chan client "node" on his desktop or server. It must be always online to serve content to his users.
2. He generates a public key pair, which will be the "address" of his 4chan board.
3. He sets up a captcha server of his choice. It must also be always online to server his users.
4. He publishes the metadata of his 4chan board to his public key based addressing. This includes board title, description, rules, list of public keys of janitors, and the captcha server URL
Note: It is possible to delegate running a client and captcha server URL to a centralized service, without providing the private key, which makes user experience easier, without sacrificing decentralization.

**Lifecycle of reading the latest posts on a 4chan board**
![7](https://user-images.githubusercontent.com/90033261/133583070-7afb3bac-4b52-4dba-af79-de81266e43ae.png)
1. User opens the 4chan app in a browser or desktop client, and sees an interface similar to 4chan.
2. His client joins the public key addressing network as a peer and makes a DHT query for each address of each board he reads regularly. The queries each take a several seconds but can be performed concurrently.
3. The query returns the latest posts of each board, as well as their metadata such as title, description, janitor list and captcha server URL.
4. His client arranges the content received in an interface similar to 4chan.

**Lifecycle of publishing a post on a 4chan board**
![6](https://user-images.githubusercontent.com/90033261/133583098-d1bb6987-bbf6-4013-b5de-7d87ad34d134.png)
1. User opens the 4chan app in a browser or desktop client, and sees an interface similar to 4chan.
2. The app automatically generates a public key pair if the user doesn't already have one.
3. He publishes an anime post for a board called "/a/" with the public key "Y2F0cyA..."
4. The app makes a call to "Y2F0cyA..." board's captcha server. The captcha server optionally decides to send the user a captcha challenge. User completes it and includes the captcha server's signature with his post.
5. His client joins the pubsub network for "Y2F0cyA..." and publishes his post.
6. The 4chan board owner's client gets notified that the user published to his pubsub, the post is not ignored because it contains his valid captcha server signature.
7. The 4chan board owner's client updates the content of his board's public key based addressing automatically.
8. A few minutes later, each user reading the board receives the update in their app.
9. If the user's post violates the board's rules, a janitor can delete it, using a similar process the user used to publish.
Note: Browser users cannot join peer-to-peer networks directly, but they can use an HTTP provider or gateway that relays data for them. This service can exist for free without users having to do or pay anything.

**What is a "post"**

Post content is not retrieved directly by querying a board's public key. What is retrieved is list of "content based addressing" fields. Example: latest post: "bGF0ZXN0...", metadata: "bWV0YWRhdGE...". The client will then perform a DHT query to retrieve the content. At least one peer should have the data: the board's owner client node. If a board is popular, many other peers will have it and the load will be distributed, like on Bittorrent.

**Peer-to-peer pubsub scalability**

A peer-to-peer pubsub network is susceptible to spam and does not scale well. Pubsub peers who spam messages without a valid captcha server signature can be blacklisted. And captcha server URLs can be behind DDOS protection services like Cloudflare, so it should be possible for board owners to resist spam attacks without too much difficulty.

**Captcha server lifecycle**

1. The app loads the captcha server URL in an iframe before publishing a post. This URL is operated by each subplebbit owner individually.
2. The server sends a visual or audio challenge and it appears inside the iframe. The server can skip this step and go to step 4 if it trusts the user and/or IP.
3. The user completes the challenge and sends his answer back to the server.
4. If the challenge answer is correct, the server sends back a digital signature for the post.
5. The user can now include this signature with his post, and when the board owner encounters that post in the pubsub network, he knows it is not spam.

**Conclusion**

We believe that the design above would solve the problems of a serverless, adminless decentralized 4chan alternative. It would allow unlimited amounts of boards, users, posts and replies. This is achieved by not caring about the order or availability of old data. It would allow users to post for free using an identical 4chan interface. It would allow board owners to moderate spam semi-automatically using their own captcha server implementations. It would allow for all features that make 4chan addictive: (Yous), replies, thumbnails, bumps. Finally, it would allow the 4chan client developers to serve an unlimited amount of users, without any server, legal, advertising or moderation infrastructure.

If you have any question my contact is in my bio.

**Comment by opatdchan** [comment]
From a quick read this seems similar to [secure scuttlebutt](https://en.wikipedia.org/wiki/Secure_Scuttlebutt). I initially considered it, but I had to discard it because it was too clunky of a solution, as it would have needed to be its own client instead of a simply being a web page.
I am sure that these solutions are better from a decentralization/privacy/uncensorability standpoint, but it would completely kill the usability. It first needs to run in a web browser.

**Comment by estebanabaroa** [comment]
> From a quick read this seems similar to [secure scuttlebutt](https://en.wikipedia.org/wiki/Secure_Scuttlebutt). I initially considered it, but I had to discard it because it was too clunky of a solution, as it would have needed to be its own client instead of a simply being a web page.
> I am sure that these solutions are better from a decentralization/privacy/uncensorability standpoint, but it would completely kill the usability. It first needs to run in a web browser.

It doesn't need a desktop client any more than IPFS, Ethereum, Bitcoin or even Matic/The Graph. When you interact with IPFS or Ethereum or Bitcoin in your browser, you're going through an HTTP bridge. In Ethereum it is called "HTTP provider", the most popular being Infura. In IPFS it's called "HTTP gateway", the most popular one I believe being run by Cloudflare.

I'm not familiar with Matic or The Graph but since it's closely related to Ethereum and Metamask I'm guessing they also use the "HTTP Provider" terminology. So dchan already uses an "HTTP bridge" to work in the browser. My design idea would also use such a bridge (as all cryptocurrencies do and IPFS does), so would provide the exact same usability as you currently have, but it would also be free to post and infinitely scalable.

In my design idea I described how the protocol would work underneath the "HTTP bridge" because that's where the action happens. 

Also in terms of ease of implementation for your team, IPFS already has an implementation of "public key addressing network" called IPNS https://docs.ipfs.io/concepts/ipns/ as well as an experimental pubsub implementation https://docs.ipfs.io/reference/cli/#ipfs-pubsub-pub. Both could be use to build an MVP quickly.

**Comment by opatdchan** [comment]
While an interesting idea, this is a fundamentally different approach than the current one and way out of scope for the project as it stands.
You can try to hack it into the client somehow though.
